name: Maven Project CI
run-name: "${{github.actor}} is running Maven Project CI # ${{github.run_number}}"
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Step 1. Checkout branch
      uses: actions/checkout@v3
    - name: Step 2. Setup JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.17
    - name: Step 3. Build Maven Project
      run: mvn -B package --file pom.xml
    - name: Step 4. List current directory
      run: ls -a
    - name: Step 5. What is in the target directory?
      run: |
        cd target
        ls -a
  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Step 1. Checkout branch
      uses: actions/checkout@v3
    - name: Step 2. Setup JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.17
    - name: Step 3. Build Maven Project
      run: mvn -B package --file pom.xml
    - name: Step 4. List current directory
      run: ls -a
    - name: Step 5. What is in the target directory?
      run: |
        cd target
        ls -a
        
  build-on-mac:
    runs-on: macos-latest
    steps:
    - name: Step 1. Checkout branch
      uses: actions/checkout@v3
    - name: Step 2. Setup JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.17
    - name: Step 3. Build Maven Project
      run: mvn -B package --file pom.xml
    - name: Step 4. List current directory
      run: ls -a
    - name: Step 5. What is in the target directory?
      run: |
        cd target
        ls -a
