name: Maven Project CI
run-name: "${{github.actor}} is running Maven Project CI # ${{github.run_number}}"
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.17
    - name: Single line script
      run: echo "Hello world"
